/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FilterConfigurationSchema = {
  pull_request: {
    /**
     * Permitted actions
     */
    actions: (
      | "assigned"
      | "auto_merge_disabled"
      | "auto_merge_enabled"
      | "closed"
      | "converted_to_draft"
      | "edited"
      | "labeled"
      | "locked"
      | "opened"
      | "ready_for_review"
      | "reopened"
      | "review_request_removed"
      | "review_requested"
      | "synchronize"
      | "unassigned"
      | "unlabeled"
      | "unlocked"
    )[];
    /**
     * List of black listed users
     */
    "users-black-listed": string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
