/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TeamSchema {
  /**
   * Permitted actions
   */
  actions: ("created" | "deleted" | "edited" | "added_to_repository" | "removed_from_repository")[];
  [k: string]: unknown;
}
