/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReleaseSchema {
  action: "published" | "unpublished" | "created" | "edited" | "deleted" | "prereleased" | "released";
  sender: {
    login: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
